[package]
name = "ch34x_paly"
version = "0.1.0"
edition = "2024"

[dependencies]
async-io = "2.4.0"
env_logger = "0.11.8"
futures-lite = "2.6.0"
log = "0.4.27"
nusb = "0.1.14"
probe-rs = "0.28.0"
smol = "2.0.2"
# tracing = "0.1.41"
